import { Injectable } from '@nestjs/common';
import { NlpManager, NerManager, NlpUtil } from 'node-nlp';
@Injectable()
export class NlpService {
  private manager = new NlpManager({ languages: ['en'] });
  constructor() {

    this.manager.addDocument('en', 'I want to change the address for delivery of my order.', 'faq.change-address');
    this.manager.addDocument('en', 'How can I modify or add an alternate number for the order delivery?', 'faq.modify-number');
    this.manager.addDocument('en', 'Can I get my orders delivered at a specific time?', 'faq.specific-time');
    this.manager.addDocument('en', 'Where can I get the delivery executive\'s contact details?', 'faq.delivery-contact');
    this.manager.addDocument('en', 'Can I get my order delivered faster?', 'faq.faster-delivery');
    this.manager.addDocument('en', 'How do I return my order on Flipkart?', 'faq.return-order');
    this.manager.addDocument('en', 'How do I place a request for order replacement?', 'faq.place-replacement-request');
    this.manager.addDocument('en', 'What is the Flipkart return policy for cash on delivery?', 'faq.cod-return-policy');
    this.manager.addDocument('en', 'Can I ask the delivery agent to reschedule the pickup date?', 'faq.reschedule-pickup');
    this.manager.addDocument('en', 'What if I miss my Flipkart order pickup?', 'faq.missed-pickup');
    this.manager.addDocument('en', 'How do I contact the seller?', 'faq.contact-seller');
    this.manager.addDocument('en', 'How do I know my order has been confirmed?', 'faq.order-confirmation');
    this.manager.addDocument('en', 'Hello', 'greet.hello');
    this.manager.addDocument('en', 'Hi', 'greet.hi');
    this.manager.addDocument('en', 'Hey', 'greet.hey');
    this.manager.addDocument('en', 'Good morning', 'greet.good-morning');
    this.manager.addDocument('en', 'Good afternoon', 'greet.good-afternoon');
    this.manager.addDocument('en', 'Good evening', 'greet.good-evening');
    this.manager.addDocument('en', 'How are you?', 'greet.how-are-you');
    this.manager.addDocument('en', 'What are the modes of refund available after cancellation?', 'faq.refund-modes');
    this.manager.addDocument('en', 'I have still not received the refund in my bank account.', 'faq.not-received-refund');
    this.manager.addDocument('en', 'Why does it take time for the refund amount to be credited when it was already processed by Flipkart?', 'faq.refund-processing-time');
    this.manager.addDocument('en', 'When are refunds given?', 'faq.when-refunds-given');
    this.manager.addDocument('en', 'How will I get my refund for returning an item I paid for with Cash on Delivery?', 'faq.cod-refund');
    this.manager.addDocument('en', 'Will I get a complete refund if the item is cancelled or returned if I have paid for the order using the \'Credit Card No Cost EMI\' payment option?', 'faq.emi-refund');
    this.manager.addDocument('en', "I see the 'Cancel' button but I can't click on it. Why?", 'faq.cannot-click-cancel-button');
    this.manager.addDocument('en', 'Can I modify/change the specification for the ordered product without cancelling it?', 'faq.modify-product-spec');
    this.manager.addDocument('en', 'How can I track my order?', 'faq.track-order');
    this.manager.addDocument('en', 'What is the return process?', 'faq.return-process');
    this.manager.addDocument('en', 'Tell me about your shipping options.', 'faq.shipping-options');
    this.manager.addDocument('en', 'Can I cancel my order?', 'faq.cancel-order');
    this.manager.addDocument('en', 'How do I change my payment method?', 'faq.change-payment-method');
    this.manager.addDocument('en', 'What is your customer support contact?', 'faq.customer-support-contact');
    this.manager.addDocument('en', 'How do I leave a review for a product?', 'faq.leave-review');
    this.manager.addDocument('en', 'Tell me about your loyalty program.', 'faq.loyalty-program');
    this.manager.addDocument('en', 'Can I change my delivery address after the order has been shipped?', 'faq.change-address-after-shipping');
    this.manager.addDocument('en', 'What is the delivery time for standard shipping?', 'faq.standard-shipping-time');
    this.manager.addDocument('en', 'What is your policy on product warranties?', 'faq.product-warranty-policy');
    this.manager.addDocument('en', 'How can I unsubscribe from promotional emails?', 'faq.unsubscribe-promotional-emails');
    this.manager.addDocument('en', 'Tell me about your privacy policy.', 'faq.privacy-policy');
    this.manager.addDocument('en', 'Can I change the delivery date for my order?', 'faq.change-delivery-date');
    this.manager.addDocument('en', 'How can I return a gift I received?', 'faq.return-gift');
    this.manager.addDocument('en', 'Tell me about your rewards program for loyal customers.', 'faq.loyal-customer-rewards');
    this.manager.addDocument('en', 'How can I check my order history?', 'faq.check-order-history');
    this.manager.addDocument('en', 'What is your policy on returns for perishable items?', 'faq.perishable-items-return-policy');
    this.manager.addDocument('en', 'Can I change the delivery address for a future order?', 'faq.change-future-delivery-address');
    this.manager.addDocument('en', 'Tell me about your mobile app.', 'faq.mobile-app-info');
    this.manager.addDocument('en', 'Tell me about your subscription services.', 'faq.subscription-services');
    this.manager.addDocument('en', 'How can I contact your technical support team?', 'faq.contact-technical-support');
    this.manager.addDocument('en', 'What is your policy on order cancellations?', 'faq.order-cancellation-policy');
    this.manager.addDocument('en', 'Can I change the shipping method for an existing order?', 'faq.change-shipping-method');
    this.manager.addDocument('en', 'Tell me about your gift wrapping options.', 'faq.gift-wrapping-options');
    this.manager.addDocument('en', 'How can I find the latest deals and discounts?', 'faq.latest-deals-discounts');
    this.manager.addDocument('en', 'Tell me about your product ratings and reviews system.', 'faq.product-ratings-reviews');
    this.manager.addDocument('en', 'What is your policy on returns for clothing items?', 'faq.clothing-returns-policy');
    this.manager.addDocument('en', 'Can I add multiple addresses to my account?', 'faq.multiple-addresses-account');
    this.manager.addDocument('en', 'Tell me about your customer referral program.', 'faq.customer-referral-program');
    this.manager.addDocument('en', 'Tell me about your loyalty program for repeat customers.', 'faq.repeat-customer-loyalty-program');
    this.manager.addDocument('en', 'How can I update my billing information?', 'faq.update-billing-information');
    this.manager.addDocument('en', 'What is your policy on order tracking delays?', 'faq.order-tracking-delays-policy');
    this.manager.addDocument('en', 'Can I return a product without the original packaging?', 'faq.return-without-original-packaging');
    this.manager.addDocument('en', 'Tell me about your mobile app features.', 'faq.mobile-app-features');
    this.manager.addDocument('en', 'Do you offer gift cards?', 'faq.gift-cards');
    this.manager.addDocument('en', 'How do I unsubscribe from SMS notifications?', 'faq.unsubscribe-sms-notifications');
    this.manager.addDocument('en', 'What is your exchange policy for apparel items?', 'faq.apparel-exchange-policy');
    this.manager.addDocument('en', 'Can I change my delivery time slot for an upcoming order?', 'faq.change-delivery-time-slot');
    this.manager.addDocument('en', 'Tell me about your order packaging materials.', 'faq.order-packaging-materials');
    this.manager.addDocument('en', 'Tell me about your product availability in my area.', 'faq.product-availability');
    this.manager.addDocument('en', 'How can I provide feedback on my shopping experience?', 'faq.provide-feedback');
    this.manager.addDocument('en', 'What is your policy on delayed deliveries?', 'faq.delayed-deliveries-policy');
    this.manager.addDocument('en', 'Can I modify the quantity of items in my order?', 'faq.modify-order-quantity');
    this.manager.addDocument('en', 'Tell me about your order status notifications.', 'faq.order-status-notifications');
    this.manager.addDocument('en', 'Do you offer international returns?', 'faq.international-returns');
    this.manager.addDocument('en', 'How do I reset my password?', 'faq.reset-password');
    this.manager.addDocument('en', 'What is your policy on lost packages?', 'faq.lost-packages-policy');
    this.manager.addDocument('en', 'Can I change the payment method for a pending order?', 'faq.change-payment-method-pending-order');
    this.manager.addDocument('en', 'Tell me about your seller rating system.', 'faq.seller-rating-system');
    this.manager.addDocument('en', 'How can I contact your legal department?', 'faq.contact-legal-department');
    this.manager.addDocument('en', 'What is your policy on price adjustments?', 'faq.price-adjustments-policy');
    this.manager.addDocument('en', 'Can I return a digital product?', 'faq.return-digital-product');
    this.manager.addDocument('en', 'How can I apply a discount code to my order?', 'faq.apply-discount-code');
    this.manager.addDocument('en', 'Tell me about your charity partnerships.', 'faq.charity-partnerships');
    this.manager.addDocument('en', 'Do you offer bulk purchasing discounts?', 'faq.bulk-purchasing-discounts');
    this.manager.addDocument('en', 'What is your policy on order substitutions?', 'faq.order-substitutions-policy');
    this.manager.addDocument('en', 'Can I add a personalized message to a gift order?', 'faq.personalized-message-gift-order');
    this.manager.addDocument('en', 'Tell me about your product return pickup service.', 'faq.return-pickup-service');
    this.manager.addDocument('en', 'How do I request a refund for a canceled order?', 'faq.refund-for-canceled-order');
    this.manager.addDocument('en', 'Tell me about your return policy for electronics.', 'faq.electronics-return-policy');
    this.manager.addDocument('en', 'What is your policy on damaged items?', 'faq.damaged-items-policy');
    this.manager.addDocument('en', 'How can I change my email address in my account?', 'faq.change-email-address');
    this.manager.addDocument('en', 'Do you offer international shipping?', 'faq.international-shipping');
    this.manager.addDocument('en', 'What are the accepted payment methods?', 'faq.payment-methods');

    this.manager.addAnswer('en', 'faq.product-availability', 'Product availability in your area may vary. You can check product availability by entering your location on the product page.');
    this.manager.addAnswer('en', 'faq.provide-feedback', 'You can provide feedback on your shopping experience by visiting our website and using the feedback form.');
    this.manager.addAnswer('en', 'faq.delayed-deliveries-policy', 'Our policy on delayed deliveries is to ensure that you receive your order as soon as possible. If there are delays, please contact our customer support for assistance.');
    this.manager.addAnswer('en', 'faq.modify-order-quantity', 'You can modify the quantity of items in your order if its still in the processing stage. Look for the option to edit the order details.');
    this.manager.addAnswer('en', 'faq.order-status-notifications', 'We provide order status notifications via email and SMS. You can also check the status of your order in your account.');
    this.manager.addAnswer('en', 'faq.international-returns', 'International returns may have specific requirements. Please review our international returns policy for details.');
    this.manager.addAnswer('en', 'faq.reset-password', 'To reset your password, go to the login page and look for the "Forgot Password" link. Follow the instructions to reset your password.');
    this.manager.addAnswer('en', 'faq.lost-packages-policy', 'If your package is lost, please contact our customer support. We will investigate and take appropriate action.');
    this.manager.addAnswer('en', 'faq.change-payment-method-pending-order', 'You can change the payment method for a pending order if its still in the processing stage. Look for the option to edit the payment method.');
    this.manager.addAnswer('en', 'faq.seller-rating-system', 'Our seller rating system allows customers to rate and review sellers based on their shopping experiences. Seller ratings help other customers make informed decisions.');
    this.manager.addAnswer('en', 'faq.contact-legal-department', 'To contact our legal department, please visit our Contact Us page on the website, where you can find contact information for legal inquiries.');
    this.manager.addAnswer('en', 'faq.price-adjustments-policy', 'Our policy on price adjustments may vary by product category. Please review the product page for specific price adjustment information.');
    this.manager.addAnswer('en', 'faq.return-digital-product', 'Digital products may have specific return policies. Please review the product page and digital product return policy for details.');
    this.manager.addAnswer('en', 'faq.apply-discount-code', 'To apply a discount code to your order, enter the code during the checkout process in the "Apply Coupon" or "Promo Code" field.');
    this.manager.addAnswer('en', 'faq.charity-partnerships', 'We have partnerships with various charities to support causes we care about. You can learn more about our charity partnerships on our website.');
    this.manager.addAnswer('en', 'faq.bulk-purchasing-discounts', 'We offer bulk purchasing discounts for select products. You can find information about bulk discounts on the product page.');
    this.manager.addAnswer('en', 'faq.order-substitutions-policy', 'Our policy on order substitutions may vary. Please review the product page and order substitutions policy for details.');
    this.manager.addAnswer('en', 'faq.personalized-message-gift-order', 'You can add a personalized message to a gift order during the checkout process. Look for the option to include a gift message.');
    this.manager.addAnswer('en', 'faq.return-pickup-service', 'We offer a product return pickup service for select locations. You can request a pickup during the return process.');
    this.manager.addAnswer('en', 'faq.refund-for-canceled-order', 'If your order is canceled, a refund will be processed to the original payment method used during the order placement.');
    this.manager.addAnswer('en', 'faq.repeat-customer-loyalty-program', 'Our loyalty program for repeat customers offers exclusive discounts and rewards based on your purchase history. You can enroll in the program by creating an account.');
    this.manager.addAnswer('en', 'faq.update-billing-information', 'You can update your billing information in your account settings. Look for the option to edit your billing details.');
    this.manager.addAnswer('en', 'faq.order-tracking-delays-policy', 'If there are delays in order tracking, it may be due to factors like courier delays. Please allow some extra time for tracking updates.');
    this.manager.addAnswer('en', 'faq.return-without-original-packaging', 'You can usually return a product without the original packaging, but its best to check the specific return policy for the item on the product page.');
    this.manager.addAnswer('en', 'faq.mobile-app-features', 'Our mobile app offers features like one-click ordering, real-time order tracking, and exclusive app-only discounts.');
    this.manager.addAnswer('en', 'faq.gift-cards', 'Yes, we offer gift cards that can be used as a payment method during checkout.');
    this.manager.addAnswer('en', 'faq.unsubscribe-sms-notifications', 'To unsubscribe from SMS notifications, reply "STOP" to any SMS message you receive from us.');
    this.manager.addAnswer('en', 'faq.apparel-exchange-policy', 'Our exchange policy for apparel items allows exchanges within 30 days of delivery, provided the items are in their original condition.');
    this.manager.addAnswer('en', 'faq.change-delivery-time-slot', 'You can change your delivery time slot for an upcoming order if its still in the processing stage. Look for the option to reschedule the delivery.');
    this.manager.addAnswer('en', 'faq.order-packaging-materials', 'We use eco-friendly packaging materials to minimize our environmental impact.');
    this.manager.addAnswer('en', 'faq.latest-deals-discounts', 'You can find the latest deals and discounts by visiting our "Deals" or "Offers" section on our website or mobile app.');
    this.manager.addAnswer('en', 'faq.product-ratings-reviews', 'Our product ratings and reviews system allows customers to share their feedback and experiences with our products. You can read reviews on individual product pages.');
    this.manager.addAnswer('en', 'faq.clothing-returns-policy', 'Our returns policy for clothing items allows returns within 30 days of delivery, provided the items are in their original condition with tags.');
    this.manager.addAnswer('en', 'faq.multiple-addresses-account', 'Yes, you can add multiple addresses to your account for shipping convenience. Look for the option to manage addresses in your account settings.');
    this.manager.addAnswer('en', 'faq.customer-referral-program', 'Our customer referral program rewards you for referring friends and family to our platform. You can find more information about the program on our website.');
    this.manager.addAnswer('en', 'faq.subscription-services', 'Our subscription services offer convenience and savings for products you use regularly. You can find more information on available subscriptions on our website.');
    this.manager.addAnswer('en', 'faq.contact-technical-support', 'For technical support, please visit our Contact Us page on the website, where you can find contact information for our technical support team.');
    this.manager.addAnswer('en', 'faq.order-cancellation-policy', 'You can cancel an order if it has not been shipped yet. Once an order is shipped, it cannot be canceled. Please review our order cancellation policy for more details.');
    this.manager.addAnswer('en', 'faq.change-shipping-method', 'You can change the shipping method for an existing order if its still in the "Approved/Processing" status. Go to the Orders page and look for the option to change the shipping method.');
    this.manager.addAnswer('en', 'faq.gift-wrapping-options', 'We offer gift wrapping options during the checkout process. You can select gift wrapping for eligible items and add a personalized message for the recipient.');
    this.manager.addAnswer('en', 'faq.loyal-customer-rewards', 'Our rewards program offers exclusive discounts and perks to our loyal customers. You can join the program by signing up for an account and making regular purchases.');
    this.manager.addAnswer('en', 'faq.check-order-history', 'To check your order history, log in to your account and go to the "Order History" or "My Orders" section. There, you can view details of your past orders.');
    this.manager.addAnswer('en', 'faq.perishable-items-return-policy', 'Perishable items may have specific return policies due to their nature. Please check the product page and return policy for perishable items for details.');
    this.manager.addAnswer('en', 'faq.change-future-delivery-address', 'You can change the delivery address for a future order during the checkout process. Look for the option to edit the delivery address.');
    this.manager.addAnswer('en', 'faq.mobile-app-info', 'Our mobile app provides a convenient way to shop online, track orders, and receive exclusive app-only offers. You can download the app from your device\'s app store.');
    this.manager.addAnswer('en', 'faq.product-warranty-policy', 'Our product warranty policy varies by product category. Please refer to the product description or contact customer support for warranty details.');
    this.manager.addAnswer('en', 'faq.unsubscribe-promotional-emails', 'To unsubscribe from promotional emails, click the "Unsubscribe" link at the bottom of any promotional email you receive from us.');
    this.manager.addAnswer('en', 'faq.privacy-policy', 'You can review our privacy policy by visiting the Privacy Policy page on our website. It outlines how we handle your personal information.');
    this.manager.addAnswer('en', 'faq.change-delivery-date', 'You can change the delivery date for your order if its still in the "Approved/Processing" status. Go to the Orders page and look for the option to reschedule delivery.');
    this.manager.addAnswer('en', 'faq.return-gift', 'To return a gift you received, please contact our customer support. They will guide you through the return process and provide instructions.');
    this.manager.addAnswer('en', 'faq.customer-support-contact', 'You can reach our customer support team at 1-800-123-4567 or support@example.com. We are available 24/7 to assist you.');
    this.manager.addAnswer('en', 'faq.leave-review', 'To leave a review for a product, go to the product page, scroll down to the review section, and click on the "Write a Review" button. You can share your feedback and rate the product.');
    this.manager.addAnswer('en', 'faq.loyalty-program', 'Our loyalty program offers exclusive discounts and rewards to loyal customers. You can join our program by signing up for an account and making regular purchases.');
    this.manager.addAnswer('en', 'faq.standard-shipping-time', 'The standard shipping time varies depending on your location and the seller. Typically, it takes 3-7 business days for standard shipping.');
    this.manager.addAnswer('en', 'faq.track-order', 'You can track your order by logging into your account and going to the Orders section. There, you will find the tracking information for your order.');
    this.manager.addAnswer('en', 'faq.return-process', 'To initiate a return, go to the Orders page, select the order you want to return, and follow the instructions provided. You can choose to return for a refund, replacement, or exchange.');
    this.manager.addAnswer('en', 'faq.shipping-options', 'We offer various shipping options, including standard and express delivery. The available options may vary depending on your location and the seller.');
    this.manager.addAnswer('en', 'faq.cancel-order', 'You can cancel your order if it has not been shipped yet. Go to the Orders page, select your order, and choose the cancel option. If the order has already been shipped, you can initiate a return.');
    this.manager.addAnswer('en', 'faq.change-payment-method', 'You can change your payment method for an order that has not been shipped yet. Go to the Orders page, select your order, and look for the option to change the payment method.');
    this.manager.addAnswer('en', 'faq.electronics-return-policy', 'Our return policy for electronics allows returns within 10 days of delivery for damaged or defective items. Please check the product page for specific details.');
    this.manager.addAnswer('en', 'faq.damaged-items-policy', 'If you receive a damaged item, please contact our customer support immediately with a photo of the damage. We will assist you in getting a replacement or refund.');
    this.manager.addAnswer('en', 'faq.change-email-address', 'To change your email address, go to your account settings and look for the option to update your email. Follow the instructions to make the change.');
    this.manager.addAnswer('en', 'faq.international-shipping', 'Yes, we offer international shipping to select countries. You can check if your location is eligible for international delivery during the checkout process.');
    this.manager.addAnswer('en', 'faq.payment-methods', 'We accept various payment methods, including credit/debit cards, net banking, UPI, and Cash on Delivery. You can choose your preferred payment method during checkout.');
    this.manager.addAnswer('en', 'faq.cannot-click-cancel-button', 'A greyed-out and disabled \'Cancel\' button can mean any one of the following:\n\n1. The item has been delivered already OR\n2. The item is non-refundable (e.g., Gift Card)');
    this.manager.addAnswer('en', 'faq.modify-product-spec', 'No, once an order is placed, the specification of the product cannot be modified.');
    this.manager.addAnswer('en', 'faq.refund-modes', 'The different modes of refund available are:\n\nPayment mode: Cash on Delivery\n\n1. UPI (Amount less than Rs 1000) - Refund will be processed to the UPI account for which UPI ID has to be shared\n2. Gift Card (Amount less than Rs 10000) - Refund will be processed to Gift Card account\n3. Bank account (IMPS/NEFT) - Refund will be processed to the bank account for which bank details have to be shared\n\nPayment mode: Prepaid\n\n1. Back to source - Refund will be processed to the payment mode (Debit/Credit card, NEFT, UPI) used to pay for the order\n2. Gift Card (Amount less than Rs 10000) - Refund will be processed to the Gift Card account.');
    this.manager.addAnswer('en', 'faq.not-received-refund', 'If you have received a mail from us confirming your refund request, it means that the refund has been initiated. You can also contact your bank with the refund reference (ARN)/UTR number you would have received for an update on the status of your refund.');
    this.manager.addAnswer('en', 'faq.refund-processing-time', 'Once the refund has been processed, the bank takes some time to reverse your initial transaction and complete the refund. However, the refund amount can be seen in your account within the time frame provided to you. Please contact your bank with the refund reference/UTR number in case you don\'t see the refund amount in your account after the specified timeframe.');
    this.manager.addAnswer('en', 'faq.when-refunds-given', 'Refunds are given when:\n\n- Any prepaid order is cancelled and the amount paid is refunded automatically to the original source of payment\n- Products from select categories are returned under certain conditions. Check the seller\'s Returns Policy on the product page for more details');
    this.manager.addAnswer('en', 'faq.cod-refund', 'For your Cash on Delivery order, you will receive the refund in the form of NEFT. Please update your bank account details after you choose this option.');
    this.manager.addAnswer('en', 'faq.emi-refund', 'Yes, you will get a complete refund to the extent of the EMIs paid (if any) in case the order is cancelled or returned.\n\nHowever, banks may charge some cancellation/refund or pre-closure charges. Please check with your respective bank for their policy for cancellations, refunds, and pre-closures.\n\n*Orders for certain items cannot be cancelled after 24 hours of order placement or returned once delivered. Please check the seller\'s cancellations & returns policy on the product page for details.');
    this.manager.addAnswer('en', 'faq.change-address', 'The delivery address for your order can be changed depending on its status. Please check Orders > Order Details for the below:\n\nApproved/Processing: If this is your order status, then you can change the address through your Flipkart app.\nShipped: Only text change in your address will be possible. Pincode cannot be changed at this stage.\nDelivered: As the item would have already been delivered, the address change will not be possible.');
    this.manager.addAnswer('en', 'faq.modify-number', 'You can modify the existing delivery contact number or add an alternate one with these simple steps:\n\n- Go to Orders\n- Select the desired \'Order\'\n- Scroll down and go to shipping details tab and tap \'Edit\' (Pen) option next to the phone number');
    this.manager.addAnswer('en', 'faq.specific-time', 'Orders for a few items from certain categories like large appliances, furniture, and exercise & fitness categories can be delivered at specific time slots by the sellers\' partnered courier service providers: You can choose your preferred time slot from the list of available ones while placing your order. For other items, the seller\'s partnered courier service providers currently do not support delivery at a specific time due to their varying delivery schedules.');
    this.manager.addAnswer('en', 'greet.hello', 'Hello! How can I assist you today?');
    this.manager.addAnswer('en', 'greet.hi', 'Hi there! How can I help you?');
    this.manager.addAnswer('en', 'greet.hey', 'Hey! How can I assist you today?');
    this.manager.addAnswer('en', 'greet.good-morning', 'Good morning! How can I help you today?');
    this.manager.addAnswer('en', 'greet.good-afternoon', 'Good afternoon! How can I assist you today?');
    this.manager.addAnswer('en', 'greet.good-evening', 'Good evening! How can I help you today?');
    this.manager.addAnswer('en', 'greet.how-are-you', 'I am just a chatbot, but thanks for asking! How can I assist you today?')
    this.manager.addAnswer('en', 'faq.delivery-contact', 'Once your order is Out for delivery, you will get the delivery executive details by visiting the Orders section of your Flipkart account.')
    this.manager.addAnswer('en', 'faq.faster-delivery', 'No, the delivery date you see after the order confirmation is provided is based on factors like your address, the seller\'s address, and the time needed by couriers to process and ship your order. Due to these factors, they do not have the option to change the delivery date and have it reach you earlier. However, you can track your order and its movement easily from our app or website.');
    this.manager.addAnswer('en', 'faq.return-order', 'To return your order on Flipkart, place a return request in the Orders page. You will get an option to choose refund/replace/exchange as per our return policy.');
    this.manager.addAnswer('en', 'faq.place-replacement-request', 'To place a request for order replacement, place a return request in the Orders page. You will get an option to choose refund/replace/exchange as per our return policy.');
    this.manager.addAnswer('en', 'faq.cod-return-policy', 'In case of cash on delivery, you will have to provide a bank account number for the refund. For replacement/exchange, you will be given an alternate product for the returned product.');
    this.manager.addAnswer('en', 'faq.reschedule-pickup', 'Yes, you can schedule the pickup date based on your convenience.');
    this.manager.addAnswer('en', 'faq.missed-pickup', 'Do not worry, the delivery agent will try to pick up again on the next working day.');
    this.manager.addAnswer('en', 'faq.contact-seller', 'To contact a seller, please send a letter with the below address on the envelope and include the product page URL so it can be forwarded to the seller:\n\nTo,\n“Include Seller\'s name”\nSeller Mailbox: Contact Seller\nc/o Flipkart Internet Private Limited,\nBuildings Alyssa, Begonia & Clove,\nEmbassy Tech Village, Bengaluru 560103\nContact: 044-66904690');
    this.manager.addAnswer('en', 'faq.order-confirmation', 'Once your order has been logged and payment authorization has been received, the seller confirms receipt of the order and begins processing it.\nYou will receive an email containing the details of your order when the seller receives it and confirms the same. In this mail you will be provided with a unique Order ID (eg. OD01202130213), a listing of the item(s) you have ordered and the expected delivery time.\nYou will also be notified when the seller ships the item(s) to you. Shipping details will be provided with the respective tracking number(s).');

    this.manager.train();
  }

  async process(message: string) {
    const response = await this.manager.process('en', message);
    return response;
  }
}
