export const buyerContext='/buyer'
export const sellerContext ='/seller'
export const adminContext='/admin'
export const chatbotContext ='/chatbot'
export const userContext='/dashboard'
export const context ='/'